apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
   name: dev-images
  spec:
   capacity:
     storage: 1T
   accessModes:
   - ReadWriteMany
   nfs:
     path: /mediawiki_images
     server: 10.117.160.90
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dev-images-claim
    namespace: tfwiki-dev
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: ""
    volumeName: dev-images
    resources:
      requests:
        storage: 1T