apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    role: nfs-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mediawiki-images
      volumes:
        - name: mediawiki-images
          gcePersistentDisk:
            pdName: tfwiki-development-mediawiki-images
            fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dev
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.tfwiki-dev.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi