apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
   name: tfwiki-media-prod
  spec:
   capacity:
     storage: 1T
   accessModes:
   - ReadWriteMany
   nfs:
     path: /tfwiki
     server: 10.155.167.82
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: tfwiki-media-prod-claim
    namespace: default
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: ""
    volumeName: tfwiki-media-prod
    resources:
      requests:
        storage: 1T