apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      containers:
      - image: tfwiki/mediawiki:latest
        name: mediawiki 
        imagePullPolicy: Always
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            path: /wiki/Main_Page
            port: 80
        ports:
        - containerPort: 80
          name: mediawiki
        env:
          - name: MEMCACHED_HOST
            valueFrom:
              configMapKeyRef:
                name: mediawiki-config
                key: memcached_host
                optional: true
          - name: SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: mediawiki-config
                key: server_url
          - name: SITENAME
            valueFrom:
              configMapKeyRef:
                name: mediawiki-config
                key: sitename
                optional: true
          - name: VARNISH_HOST
            valueFrom:
              configMapKeyRef:
                name: mediawiki-config
                key: varnish_host
                optional: true
          - name: BLACKFIRE_SOCKET
            valueFrom:
              configMapKeyRef:
                name: mediawiki-config
                key: blackfire_socket
                optional: true
          - name: CAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: captcha.secret
          - name: GMAIL_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: gmail.smtp.password
                optional: true
          - name: GMAIL_SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: gmail.smtp.username
                optional: true
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: secret_key
          - name: STEAM_API_KEY
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: steam.api.key
                optional: true
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: db.password
                optional: true
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: db.database
                optional: true
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: db.host
                optional: true
          - name: DB_TYPE
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: db.type
                optional: true
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mediawiki-secret
                key: db.user
                optional: true
        volumeMounts:
          - name: mediawiki-images
            mountPath: /var/www/html/w/images
      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=tfwiki-182108:us-west1:tfwiki-production=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
        - name: mediawiki-images
          persistentVolumeClaim:
            claimName: nfs