apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: blackfire
    name: blackfire
  spec:
    ports:
    - port: 8707
      protocol: TCP
      targetPort: 8707
    selector:
      app: blackfire
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: blackfire
    name: blackfire
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: blackfire
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: blackfire
      spec:
        containers:
        - env:
          - name: BLACKFIRE_SERVER_ID
            valueFrom:
              secretKeyRef:
                key: blackfire.server.id
                name: blackfire-secret
          - name: BLACKFIRE_SERVER_TOKEN
            valueFrom:
              secretKeyRef:
                key: blackfire.server.token
                name: blackfire-secret
          image: blackfire/blackfire
          imagePullPolicy: Always
          name: blackfire
          ports:
          - containerPort: 8707
            name: blackfire
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
kind: List
metadata: {}
