apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: nfs-server
  spec:
    ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: TCP
      targetPort: 20048
    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111
    selector:
      role: nfs-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: nfs
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 500Gi
    storageClassName: ""
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata: {}
