apiVersion: v1  
kind: Service  
metadata:  
  name: varnish
spec:  
  ports:
    - name: varnish
      port: 80
      targetPort: varnish
  selector:
    app: varnish
  type: NodePort
---
apiVersion: v1  
kind: Service  
metadata:  
  name: all-varnish
spec:  
  clusterIP: None
  ports:
    - name: varnish
      port: 80
      targetPort: varnish
  selector:
    app: varnish
---
apiVersion: extensions/v1beta1
kind: Deployment  
metadata:  
  name: varnish
  labels:
    app: varnish
spec:  
  replicas: 6
  template:
    metadata:
      name: varnish
      labels:
        app: varnish
    spec:
      containers:
      - name: varnish
        image: tfwiki/varnish:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /wiki/Main_Page
            port: 80
        env:
        - name: BACKEND_HOST
          value: mediawiki
        ports:
        - name: varnish
          containerPort: 80